version: '3'
name: 'earthquake'

services:
  backend:
    image: 'earthquake-backend:latest'
    build:
      context: backend/
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - POSTRESQL_HOST=db

  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  frontend:
    image: 'earthquake-frontend:latest'
    build:
      context: frontend/
    ports:
      - '5173:80'

volumes:
  dbdata: